language: objective-c

before_install:
    - brew update
    - brew install cmake sdl libpng readline portaudio

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

#
# enable after https://github.com/travis-ci/travis-ci/issues/216 is
# resolved, currently we can either build on linux or osx, leaving
# the configuration here to adjust to the upcoming sytax later
#
# language: c
#
# compiler: gcc
#
# before_install:
#     - sudo apt-get update -qq
#     - sudo apt-get install -qq cmake libsdl1.2-dev zlib1g-dev libpng12-dev readline-common portaudio19-dev libx11-dev
#
# before_script:
#   - mkdir build
#   - cd build
#   - cmake ..
#
# script: make
